In [1]:
import pandas as pd

df=pd.read_csv(
    'products/MCC/raw/MCC_DataExport_pre-biased-transistors(MCC-pre-biased-transistors).csv',
    header=0,
    skiprows=[0,2]
)
df.columns = [' '.join(col.split()) for col in df.columns]
print(df.mean(numeric_only=True).round(2))
df.info()

R1 Typ (KΩ)       14.62
R2 Typ (KΩ)       27.54
fT(MHz)          233.74
PD(mW)           172.47
Tj [max] (°C)    150.00
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacture          248 non-null    str
 1   Product              248 non-null    str
 2   Status               248 non-null    str
 3   Compliance           248 non-null    str
 4   Number of Functions  248 non-null    str
 5   Polarity             248 non-null    str
 6   Package Type         248 non-null    str
 7   IO(mA)               248 non-null    str
 8   R1 Typ (KΩ)          248 non-null    float64
 9   R2 Typ (KΩ)          223 non-null    float64
 10  VCC(V)               248 non-null    str
 11  fT(MHz)              247 non-null    float64
 12  PD(mW)               248 non-null    int64
 13  Tj [max] (°C)        248 non-null    int64
dtypes: float64(3), int64(2), str(9)
memory usage: 27.3 KB

In [2]:
df.head(10)

,Manufacture,Product,Status,Compliance,Number of Functions,Polarity,Package Type,IO(mA),R1 Typ (KΩ),R2 Typ (KΩ),VCC(V),fT(MHz),PD(mW),Tj [max] (°C)
0,MCC (Micro Commercial Components),UMH15NHE3,Preferred,A R H,Dual(R1/R2),NPN*2,SOT-363,100,4.7,4.7,50,250.0,150,150
1,MCC (Micro Commercial Components),EMH9,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,10.0,47.0,50,200.0,150,150
2,MCC (Micro Commercial Components),UMH31NS,Active,R H,Dual(R1/R2),NPN*2,SOT-363S,100,1.0,10.0,50,250.0,150,150
3,MCC (Micro Commercial Components),EMH1,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,22.0,22.0,50,200.0,150,150
4,MCC (Micro Commercial Components),IMH31N,Active,R H,Dual(R1/R2),NPN*2,SOT23-6L,100,1.0,10.0,50,200.0,300,150
5,MCC (Micro Commercial Components),EMH10,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,2.2,47.0,50,250.0,150,150
6,MCC (Micro Commercial Components),UMH1N,Active,R H,Dual(R1/R2),NPN*2,SOT-363,100,22.0,22.0,50,250.0,150,150
7,MCC (Micro Commercial Components),UMH2N,Active,R H,Dual(R1/R2),NPN*2,SOT-363,100,47.0,47.0,50,250.0,150,150
8,MCC (Micro Commercial Components),EMH11,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,10.0,10.0,50,250.0,150,150
9,MCC (Micro Commercial Components),EMH13,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,4.7,47.0,50,250.0,150,150

In [3]:
df2=pd.read_csv(
    'products/MCC/clean/MCC_DataExport_pre-biased-transistors(MCC-pre-biased-transistors).csv',
    header=0
)

print(df2.mean(numeric_only=True).round(2))
df2.info()

R1 Typ (KΩ)       14.62
R2 Typ (KΩ)       27.54
fT(MHz)          233.74
PD(mW)           172.47
Tj [max] (°C)    150.00
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacture          248 non-null    str
 1   Product              248 non-null    str
 2   Status               248 non-null    str
 3   Compliance           248 non-null    str
 4   Number of Functions  248 non-null    str
 5   Polarity             248 non-null    str
 6   Package Type         248 non-null    str
 7   IO(mA)               248 non-null    str
 8   R1 Typ (KΩ)          248 non-null    float64
 9   R2 Typ (KΩ)          223 non-null    float64
 10  VCC(V)               248 non-null    str
 11  fT(MHz)              247 non-null    float64
 12  PD(mW)               248 non-null    int64
 13  Tj [max] (°C)        248 non-null    int64
dtypes: float64(3), int64(2), str(9)
memory usage: 27.3 KB

In [4]:
df2.head(10)

,Manufacture,Product,Status,Compliance,Number of Functions,Polarity,Package Type,IO(mA),R1 Typ (KΩ),R2 Typ (KΩ),VCC(V),fT(MHz),PD(mW),Tj [max] (°C)
0,MCC (Micro Commercial Components),UMH15NHE3,Preferred,A R H,Dual(R1/R2),NPN*2,SOT-363,100,4.7,4.7,50,250.0,150,150
1,MCC (Micro Commercial Components),EMH9,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,10.0,47.0,50,200.0,150,150
2,MCC (Micro Commercial Components),UMH31NS,Active,R H,Dual(R1/R2),NPN*2,SOT-363S,100,1.0,10.0,50,250.0,150,150
3,MCC (Micro Commercial Components),EMH1,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,22.0,22.0,50,200.0,150,150
4,MCC (Micro Commercial Components),IMH31N,Active,R H,Dual(R1/R2),NPN*2,SOT23-6L,100,1.0,10.0,50,200.0,300,150
5,MCC (Micro Commercial Components),EMH10,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,2.2,47.0,50,250.0,150,150
6,MCC (Micro Commercial Components),UMH1N,Active,R H,Dual(R1/R2),NPN*2,SOT-363,100,22.0,22.0,50,250.0,150,150
7,MCC (Micro Commercial Components),UMH2N,Active,R H,Dual(R1/R2),NPN*2,SOT-363,100,47.0,47.0,50,250.0,150,150
8,MCC (Micro Commercial Components),EMH11,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,10.0,10.0,50,250.0,150,150
9,MCC (Micro Commercial Components),EMH13,Active,R H,Dual(R1/R2),NPN*2,SOT-563,100,4.7,47.0,50,250.0,150,150