In [45]:
import pandas as pd

df=pd.read_csv(
    'products/MCC/raw/MCC_DataExport_power-mosfets(MCC-power-mosfets).csv',
    header=0,
    skiprows=[0,2]
)
df.columns = [' '.join(col.split()) for col in df.columns]
print(df.mean(numeric_only=True))
df.info()

Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω)      0.022118
Junction Temperature Tj [max] (°C)                      158.589385
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 19 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Manufacture                                           716 non-null    str
 1   Product                                               716 non-null    str
 2   Status                                                716 non-null    str
 3   Compliance                                            716 non-null    str
 4   Number of Functions                                   716 non-null    str
 5   Channel                                               716 non-null    str
 6   Package Type                                          716 non-null    str
 7   Drain-Source Voltage VDS (V)                          716 non-null    str
 8   Gate-Source Voltage VGS (V)                           716 non-null    str
 9   Drain Current ID (A)                                  716 non-null    str
 10  Drain-Source On-Resistance RDS(ON) Max @VGS=10V (Ω)   706 non-null    str
 11  Drain-Source On-Resistance RDS(ON) Max @VGS=4.5V (Ω)  390 non-null    str
 12  Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω)  11 non-null     float64
 13  Gate Threshold Voltage VGS(th) Min (V)                716 non-null    str
 14  Gate Threshold Voltage VGS(th) Max (V)                716 non-null    str
 15  ESD Diodes                                            716 non-null    str
 16  Junction Temperature Tj [max] (°C)                    716 non-null    int64
 17  Single Pulsed Avalanche Energy EAS(mJ)                692 non-null    str
 18  Pulsed Drain Current IDM(A)                           716 non-null    str
dtypes: float64(1), int64(1), str(17)
memory usage: 106.4 KB

In [46]:
df[df['Channel']=='N+P'].head(100)
# df.head(10)

,Manufacture,Product,Status,Compliance,Number of Functions,Channel,Package Type,Drain-Source Voltage VDS (V),Gate-Source Voltage VGS (V),Drain Current ID (A),Drain-Source On-Resistance RDS(ON) Max @VGS=10V (Ω),Drain-Source On-Resistance RDS(ON) Max @VGS=4.5V (Ω),Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω),Gate Threshold Voltage VGS(th) Min (V),Gate Threshold Voltage VGS(th) Max (V),ESD Diodes,Junction Temperature Tj [max] (°C),Single Pulsed Avalanche Energy EAS(mJ),Pulsed Drain Current IDM(A)
36,MCC (Micro Commercial Components),MCGD115NP10L,Preferred,R H,Dual,N+P,DFN3333-D,100/-100,±20,10/-5.5,0.115/0.325,0.125/0.350,NaN,1.3/-1.0,2.3/-2.0,No,150,8/6.1,40/-22
122,MCC (Micro Commercial Components),MCGD10NP03,Active,R H,Dual,N+P,DFN3333-D,30/-30,±20,10/-10,0.017/0.040,0.029/0.073,NaN,1.5/-1.5,2.5/-2.5,Yes,150,20/24,40/-40
270,MCC (Micro Commercial Components),MCACD032NP06L,Active,R H,Dual,N+P,PDFN5060-8D,60/-60,±20,20/-12,0.032/0.110,0.037/0.135,NaN,1.0/-1.2,2/-2.2,No,150,36/36,80/-48
271,MCC (Micro Commercial Components),MCQD028NP04L,Active,R H,Dual,N+P,SOP-8,40/-40,±20,5.1/-3.3,0.028/0.071,0.039/0.099,NaN,1.0/-1.0,2.5/-2.5,No,150,NaN,20.4/-13.2
272,MCC (Micro Commercial Components),MCQD037NP06L,Active,R H,Dual,N+P,SOP-8,60/-60,±20,4.4/-2.2,0.037/0.134,0.047/0.180,NaN,1.0/-1.0,2.0/-2.0,No,150,25/12.2,17.6/-8.8
273,MCC (Micro Commercial Components),MCACD100NP10L,Active,R H,Dual,N+P,PDFN5060-8D,100/-100,±20,10/-12,0.10/0.11,0.107/0.120,NaN,1.1/-1.0,3/-2.5,No,150,12/49,40/-48
274,MCC (Micro Commercial Components),MCQ200NP10L,Active,R H,Dual,N+P,SOP-8,100/-100,±20,4.0/-4.0,0.27/0.20,0.28/0.22,NaN,1.0/-1.0,2.5/-2.5,No,150,3.0/28,16/-16
275,MCC (Micro Commercial Components),MCQ03NP10L,Active,R H,Dual,N+P,SOP-8,100/-100,±20,5.0/-3.0,0.027/0.110,0.030/0.120,NaN,1.0/-1.0,2.5/-2.5,No,150,NaN,20/-12
276,MCC (Micro Commercial Components),MCGD016NP04L,Active,R H,Dual,N+P,DFN3333-D,40/-40,±20,\t24/-18,0.016/0.029,0.021/0.041,NaN,1.0/-1.1,2.2/-2.1,No,150,6.25/6.25,96/-72
277,MCC (Micro Commercial Components),MCGD018NP03L,Active,R H,Dual,N+P,DFN3333-D,30/-30,±20,20/-20,0.020/0.018,0.030/0.025,NaN,1.0/-1.0,2.5/-2.5,No,150,25/81,80/-80
278,MCC (Micro Commercial Components),MCQ018NP03L,Active,R H,Dual,N+P,SOP-8,30/-30,±20,7.0/-5.0,0.018/0.043,0.030/0.063,NaN,1.0/-1.0,2.2/-2.4,No,150,NaN,28/-20
428,MCC (Micro Commercial Components),MCACD12NP10YHE3,Active,A R H,Dual,N+P,PDFN5060-8D,100/-100,±20,40/-12,0.024/0.115,0.030/0.138,NaN,1.2/-1.2,2.5/-2.5,No,150,72/36,80/-40
429,MCC (Micro Commercial Components),MCQ11NP04,Active,R H,Dual,N+P,SOP-8,40/-40,±20,11/-11,0.032/0.033,0.050/0.050,NaN,1.0/-1.0,2.5/-2.5,No,150,15/45,44/-44
430,MCC (Micro Commercial Components),MCACD40NP03,Active,R H,Dual,N+P,PDFN5060-8D,30/-30,±20/±25,40/-40,0.009/0.012,0.014/0.020,NaN,1.0/-1.2,2.5/-2.7,No,150,56/90,160/-160
431,MCC (Micro Commercial Components),MCACD12NP10Y,Active,R H,Dual,N+P,DFN5060-8D,100/-100,±20,25/-12,0.026/0.120,0.030/0.130,NaN,1.2/-1.2,2.5/-2.5,No,150,64/72,100/-48
432,MCC (Micro Commercial Components),MCQ4559A,Active,R H,Dual,N+P,SOP-8,60/-60,±20,4.5/-3.5,0.045/0.080,0.050/0.115,NaN,1.0/-1.0,2.5/-2.5,No,150,24,18/-14
433,MCC (Micro Commercial Components),MCQ07NP03A,Active,R H,Dual,N+P,SOP-8,30/-30,±20,7.0/-7.0,0.018/0.023,0.030/0.034,NaN,1.0/-1.0,2.2/-2.5,No,150,NaN,28/-28
434,MCC (Micro Commercial Components),MCQ4503A,Active,R H,Dual,N+P,SOP-8,30/-30,±20,6.5/-5.0,0.03/0.06,0.04/0.09,NaN,1.2/-1,2.4/-2.5,No,150,NaN,26/-20
435,MCC (Micro Commercial Components),MCQ4503B,Active,R H,Dual,N+P,SOP-8,30/-30,±12,5.6/-4.4,0.025/0.055,0.031/0.066,NaN,0.65/-0.60,1.5/-1.4,No,150,NaN,23/-18

In [47]:
df2=pd.read_csv(
    'products/MCC/clean/MCC_DataExport_power-mosfets(MCC-power-mosfets).csv',
    header=0
)

print(df2.mean(numeric_only=True))
df2.info()

Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω)      0.022118
Junction Temperature Tj [max] (°C)                      158.589385
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 19 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Manufacture                                           716 non-null    str
 1   Product                                               716 non-null    str
 2   Status                                                716 non-null    str
 3   Compliance                                            716 non-null    str
 4   Number of Functions                                   716 non-null    str
 5   Channel                                               716 non-null    str
 6   Package Type                                          716 non-null    str
 7   Drain-Source Voltage VDS (V)                          716 non-null    str
 8   Gate-Source Voltage VGS (V)                           716 non-null    str
 9   Drain Current ID (A)                                  716 non-null    str
 10  Drain-Source On-Resistance RDS(ON) Max @VGS=10V (Ω)   706 non-null    str
 11  Drain-Source On-Resistance RDS(ON) Max @VGS=4.5V (Ω)  390 non-null    str
 12  Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω)  11 non-null     float64
 13  Gate Threshold Voltage VGS(th) Min (V)                716 non-null    str
 14  Gate Threshold Voltage VGS(th) Max (V)                716 non-null    str
 15  ESD Diodes                                            716 non-null    str
 16  Junction Temperature Tj [max] (°C)                    716 non-null    int64
 17  Single Pulsed Avalanche Energy EAS(mJ)                692 non-null    str
 18  Pulsed Drain Current IDM(A)                           716 non-null    str
dtypes: float64(1), int64(1), str(17)
memory usage: 106.4 KB

In [48]:
df[df2['Channel']=='N+P'].head(100)

,Manufacture,Product,Status,Compliance,Number of Functions,Channel,Package Type,Drain-Source Voltage VDS (V),Gate-Source Voltage VGS (V),Drain Current ID (A),Drain-Source On-Resistance RDS(ON) Max @VGS=10V (Ω),Drain-Source On-Resistance RDS(ON) Max @VGS=4.5V (Ω),Drain-Source On-Resistance RDS(ON) Max @VGS=2.5V (Ω),Gate Threshold Voltage VGS(th) Min (V),Gate Threshold Voltage VGS(th) Max (V),ESD Diodes,Junction Temperature Tj [max] (°C),Single Pulsed Avalanche Energy EAS(mJ),Pulsed Drain Current IDM(A)
36,MCC (Micro Commercial Components),MCGD115NP10L,Preferred,R H,Dual,N+P,DFN3333-D,100/-100,±20,10/-5.5,0.115/0.325,0.125/0.350,NaN,1.3/-1.0,2.3/-2.0,No,150,8/6.1,40/-22
122,MCC (Micro Commercial Components),MCGD10NP03,Active,R H,Dual,N+P,DFN3333-D,30/-30,±20,10/-10,0.017/0.040,0.029/0.073,NaN,1.5/-1.5,2.5/-2.5,Yes,150,20/24,40/-40
270,MCC (Micro Commercial Components),MCACD032NP06L,Active,R H,Dual,N+P,PDFN5060-8D,60/-60,±20,20/-12,0.032/0.110,0.037/0.135,NaN,1.0/-1.2,2/-2.2,No,150,36/36,80/-48
271,MCC (Micro Commercial Components),MCQD028NP04L,Active,R H,Dual,N+P,SOP-8,40/-40,±20,5.1/-3.3,0.028/0.071,0.039/0.099,NaN,1.0/-1.0,2.5/-2.5,No,150,NaN,20.4/-13.2
272,MCC (Micro Commercial Components),MCQD037NP06L,Active,R H,Dual,N+P,SOP-8,60/-60,±20,4.4/-2.2,0.037/0.134,0.047/0.180,NaN,1.0/-1.0,2.0/-2.0,No,150,25/12.2,17.6/-8.8
273,MCC (Micro Commercial Components),MCACD100NP10L,Active,R H,Dual,N+P,PDFN5060-8D,100/-100,±20,10/-12,0.10/0.11,0.107/0.120,NaN,1.1/-1.0,3/-2.5,No,150,12/49,40/-48
274,MCC (Micro Commercial Components),MCQ200NP10L,Active,R H,Dual,N+P,SOP-8,100/-100,±20,4.0/-4.0,0.27/0.20,0.28/0.22,NaN,1.0/-1.0,2.5/-2.5,No,150,3.0/28,16/-16
275,MCC (Micro Commercial Components),MCQ03NP10L,Active,R H,Dual,N+P,SOP-8,100/-100,±20,5.0/-3.0,0.027/0.110,0.030/0.120,NaN,1.0/-1.0,2.5/-2.5,No,150,NaN,20/-12
276,MCC (Micro Commercial Components),MCGD016NP04L,Active,R H,Dual,N+P,DFN3333-D,40/-40,±20,\t24/-18,0.016/0.029,0.021/0.041,NaN,1.0/-1.1,2.2/-2.1,No,150,6.25/6.25,96/-72
277,MCC (Micro Commercial Components),MCGD018NP03L,Active,R H,Dual,N+P,DFN3333-D,30/-30,±20,20/-20,0.020/0.018,0.030/0.025,NaN,1.0/-1.0,2.5/-2.5,No,150,25/81,80/-80
278,MCC (Micro Commercial Components),MCQ018NP03L,Active,R H,Dual,N+P,SOP-8,30/-30,±20,7.0/-5.0,0.018/0.043,0.030/0.063,NaN,1.0/-1.0,2.2/-2.4,No,150,NaN,28/-20
428,MCC (Micro Commercial Components),MCACD12NP10YHE3,Active,A R H,Dual,N+P,PDFN5060-8D,100/-100,±20,40/-12,0.024/0.115,0.030/0.138,NaN,1.2/-1.2,2.5/-2.5,No,150,72/36,80/-40
429,MCC (Micro Commercial Components),MCQ11NP04,Active,R H,Dual,N+P,SOP-8,40/-40,±20,11/-11,0.032/0.033,0.050/0.050,NaN,1.0/-1.0,2.5/-2.5,No,150,15/45,44/-44
430,MCC (Micro Commercial Components),MCACD40NP03,Active,R H,Dual,N+P,PDFN5060-8D,30/-30,±20/±25,40/-40,0.009/0.012,0.014/0.020,NaN,1.0/-1.2,2.5/-2.7,No,150,56/90,160/-160
431,MCC (Micro Commercial Components),MCACD12NP10Y,Active,R H,Dual,N+P,DFN5060-8D,100/-100,±20,25/-12,0.026/0.120,0.030/0.130,NaN,1.2/-1.2,2.5/-2.5,No,150,64/72,100/-48
432,MCC (Micro Commercial Components),MCQ4559A,Active,R H,Dual,N+P,SOP-8,60/-60,±20,4.5/-3.5,0.045/0.080,0.050/0.115,NaN,1.0/-1.0,2.5/-2.5,No,150,24,18/-14
433,MCC (Micro Commercial Components),MCQ07NP03A,Active,R H,Dual,N+P,SOP-8,30/-30,±20,7.0/-7.0,0.018/0.023,0.030/0.034,NaN,1.0/-1.0,2.2/-2.5,No,150,NaN,28/-28
434,MCC (Micro Commercial Components),MCQ4503A,Active,R H,Dual,N+P,SOP-8,30/-30,±20,6.5/-5.0,0.03/0.06,0.04/0.09,NaN,1.2/-1,2.4/-2.5,No,150,NaN,26/-20
435,MCC (Micro Commercial Components),MCQ4503B,Active,R H,Dual,N+P,SOP-8,30/-30,±12,5.6/-4.4,0.025/0.055,0.031/0.066,NaN,0.65/-0.60,1.5/-1.4,No,150,NaN,23/-18