In [24]:
import pandas as pd

df=pd.read_csv(
    'products/MCC/raw/MCC_DataExport_bridge-rectifiers(MCC-bridge-rectifiers).csv',
    header=0,
    skiprows=[0,2]
)

df.columns = [' '.join(col.split()) for col in df.columns]
print(df.mean(numeric_only=True).round(2))
df.info()

IF(AV)(A)              15.96
VRWM (V)              856.40
VF (V) [max]@IF(A)      1.06
IR (uA) [max] @ VR     10.27
IFSM (A)              224.47
IF(A)                   8.00
VR (V)                856.40
Tj [max] (°C)         149.59
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacture          422 non-null    str
 1   Product              422 non-null    str
 2   Status               422 non-null    str
 3   Compliance           422 non-null    str
 4   Number of Functions  422 non-null    str
 5   Package Type         422 non-null    str
 6   IF(AV)(A)            422 non-null    float64
 7   VRWM (V)             422 non-null    int64
 8   VF (V) [max]@IF(A)   422 non-null    float64
 9   IR (uA) [max] @ VR   422 non-null    int64
 10  IFSM (A)             422 non-null    int64
 11  IF(A)                422 non-null    float64
 12  VR (V)               422 non-null    int64
 13  Tj [max] (°C)        422 non-null    int64
dtypes: float64(3), int64(5), str(6)
memory usage: 46.3 KB

In [15]:
df.head(10)

,Manufacture,Product,Status,Compliance,Number of Functions,Package Type,IF(AV)(A),VRWM (V),VF (V) [max]@IF(A),IR (uA) [max] @ VR,IFSM (A),IF(A),VR (V),Tj [max] (°C)
0,MCC (Micro Commercial Components),GBU1016,Preferred,R H,1-Phase Bridge,GBU,10.0,1600,1.05,5,150,5.0,1600,150
1,MCC (Micro Commercial Components),GBU2516,Preferred,R H,1-Phase Bridge,GBU,25.0,1600,1.10,5,280,12.5,1600,150
2,MCC (Micro Commercial Components),GBU3516,Preferred,R H,1-Phase Bridge,GBU,35.0,1600,1.05,5,450,17.5,1600,150
3,MCC (Micro Commercial Components),GBU5016,Preferred,R H,1-Phase Bridge,GBU,50.0,1600,1.05,5,500,25.0,1600,150
4,MCC (Micro Commercial Components),GBU3016,Preferred,R H,1-Phase Bridge,GBU,30.0,1600,1.05,5,350,15.0,1600,150
5,MCC (Micro Commercial Components),TBL1008E,Preferred,R H,1-Phase Bridge,TBL,10.0,800,0.92,5,160,5.0,800,150
6,MCC (Micro Commercial Components),TBL808EA,Preferred,R H,1-Phase Bridge,TBL,8.0,800,0.90,5,160,4.0,800,150
7,MCC (Micro Commercial Components),KBJ806GL,Preferred,R H,1-Phase Bridge,KBJ,8.0,600,0.92,5,175,4.0,600,150
8,MCC (Micro Commercial Components),KBJ808GL,Preferred,R H,1-Phase Bridge,KBJ,8.0,800,0.92,5,175,4.0,800,150
9,MCC (Micro Commercial Components),KBJ2010G,Preferred,R H,1-Phase Bridge,KBJ,20.0,1000,1.00,5,250,10.0,1000,150

In [25]:
df2=pd.read_csv(
    'products/MCC/clean/MCC_DataExport_bridge-rectifiers(MCC-bridge-rectifiers).csv',
    header=0
)

print(df2.mean(numeric_only=True).round(2))
df2.info()

IF(AV)(A)              15.96
VRWM (V)              856.40
VF (V) [max]@IF(A)      1.06
IR (uA) [max] @ VR     10.27
IFSM (A)              224.47
IF(A)                   8.00
VR (V)                856.40
Tj [max] (°C)         149.59
dtype: float64
<class 'pandas.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacture          422 non-null    str
 1   Product              422 non-null    str
 2   Status               422 non-null    str
 3   Compliance           422 non-null    str
 4   Number of Functions  422 non-null    str
 5   Package Type         422 non-null    str
 6   IF(AV)(A)            422 non-null    float64
 7   VRWM (V)             422 non-null    int64
 8   VF (V) [max]@IF(A)   422 non-null    float64
 9   IR (uA) [max] @ VR   422 non-null    int64
 10  IFSM (A)             422 non-null    int64
 11  IF(A)                422 non-null    float64
 12  VR (V)               422 non-null    int64
 13  Tj [max] (°C)        422 non-null    int64
dtypes: float64(3), int64(5), str(6)
memory usage: 46.3 KB

In [17]:
df2.head(10)

,Manufacture,Product,Status,Compliance,Number of Functions,Package Type,IF(AV)(A),VRWM (V),VF (V) [max]@IF(A),IR (uA) [max] @ VR,IFSM (A),IF(A),VR (V),Tj [max] (°C)
0,MCC (Micro Commercial Components),GBU1016,Preferred,R H,1-Phase Bridge,GBU,10.0,1600,1.05,5,150,5.0,1600,150
1,MCC (Micro Commercial Components),GBU2516,Preferred,R H,1-Phase Bridge,GBU,25.0,1600,1.10,5,280,12.5,1600,150
2,MCC (Micro Commercial Components),GBU3516,Preferred,R H,1-Phase Bridge,GBU,35.0,1600,1.05,5,450,17.5,1600,150
3,MCC (Micro Commercial Components),GBU5016,Preferred,R H,1-Phase Bridge,GBU,50.0,1600,1.05,5,500,25.0,1600,150
4,MCC (Micro Commercial Components),GBU3016,Preferred,R H,1-Phase Bridge,GBU,30.0,1600,1.05,5,350,15.0,1600,150
5,MCC (Micro Commercial Components),TBL1008E,Preferred,R H,1-Phase Bridge,TBL,10.0,800,0.92,5,160,5.0,800,150
6,MCC (Micro Commercial Components),TBL808EA,Preferred,R H,1-Phase Bridge,TBL,8.0,800,0.90,5,160,4.0,800,150
7,MCC (Micro Commercial Components),KBJ806GL,Preferred,R H,1-Phase Bridge,KBJ,8.0,600,0.92,5,175,4.0,600,150
8,MCC (Micro Commercial Components),KBJ808GL,Preferred,R H,1-Phase Bridge,KBJ,8.0,800,0.92,5,175,4.0,800,150
9,MCC (Micro Commercial Components),KBJ2010G,Preferred,R H,1-Phase Bridge,KBJ,20.0,1000,1.00,5,250,10.0,1000,150